scrapy crawl aquanaut -O aquanaut.json
scrapy crawl diveguide -O diveguide.json
scrapy crawl diventures -O diventures.json
scrapy crawl BCDivingClubs -O BCDivingClubs.json
scrapy crawl dive_centers_worldwide -O dive_centers_worldwide.json
scrapy crawl bsac -O bsac.json
scrapy crawl diving_ie -O diving_ie.json
scrapy crawl dive_ni -O dive_ni.json
scrapy crawl mlssa -O mlssa.json
scrapy crawl nabs -O nabs.json
scrapy crawl ocascuba -O ocascuba.json
scrapy crawl underwater -O underwater.json
